### ISSUE TITLE
SRS Return: connect ECONNREFUSED

### ISSUE THREAD

**Issue by jeanofthedead** [haywirecoder/homebridge-smartdrylocal#1]
Thanks so much for this plug-in. It was working for me yesterday, but today I am receiving the following error in Homebridge:

`SmartDry SRS return:  connect ECONNREFUSED`

Any idea what I need to do? I have a reserved IP address for my ESP32 device, so the IP address hasn't changed or anything.

**Comment by haywirecoder** [comment]
Hi

Hmm... Can you access the module from your browser? It should be able to see the status information about your module.

**Comment by jeanofthedead** [comment]
I cannot. Turns out I am getting an error after the device connects to WiFi:

[api.connection:075]: : Socket operation failed: BAD_INDICATOR errno=11
[api.connection:075]: Socket operation failed: CONNECTION_CLOSED errno=128

I realized that I am no longer running Home Assistant, so I guess I don't have an ESPHome web server any longer. I'm hoping to just use Homebridge going forward - do you have an example firmware that I could flash onto my ESP32 to be used with HB only? Or do I need an ESPHome server?

Thanks for your help - I'm new to ESP32, but very familiar with HA, HB.

**Comment by haywirecoder** [comment]
Below is where I posted the instruction I use and yaml that represents the firmware that used in ESPHome.  

https://github.com/haywirecoder/homebridge-smartdrylocal/tree/main/ESPHome

**Comment by jeanofthedead** [comment]
Wow, thank you so much for writing that guide. I got it working and it's awesome! I appreciate your hard work.

**Comment by haywirecoder** [comment]
Great.
